
package com.java.opts.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1.6
 * 
 */
@XmlRootElement(name = "soapFault", namespace = "http://opts.java.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TicketDetailsNotFoundException", namespace = "http://opts.java.com/", propOrder = {
    "errorModel",
    "message"
})
public class TicketDetailsNotFoundExceptionBean {

    private com.java.exception.ErrorModel errorModel;
    private String message;

    /**
     * 
     * @return
     *     returns ErrorModel
     */
    public com.java.exception.ErrorModel getErrorModel() {
        return this.errorModel;
    }

    /**
     * 
     * @param errorModel
     *     the value for the errorModel property
     */
    public void setErrorModel(com.java.exception.ErrorModel errorModel) {
        this.errorModel = errorModel;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * 
     * @param message
     *     the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

}
